<a href="https://colab.research.google.com/github/davidromero2534582021/etl-data-pipeline-2534582021/blob/main/etl_data_pipeline_2534582021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CARGA DE DATOS

Enlace de repositorio de GitHub
https://github.com/davidromero2534582021/etl-data-pipeline-2534582021/tree/main

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import re

In [55]:
from google.colab import files

In [4]:
#Ruta del D_departamentos
url_departamentos = "https://raw.githubusercontent.com/davidromero2534582021/etl-data-pipeline-2534582021/refs/heads/main/data/raw/D_departamentos.csv"
url_empleados = "https://raw.githubusercontent.com/davidromero2534582021/etl-data-pipeline-2534582021/refs/heads/main/data/raw/D_empleados.csv"
url_salarios = "https://raw.githubusercontent.com/davidromero2534582021/etl-data-pipeline-2534582021/refs/heads/main/data/raw/D_salarios.csv"

In [5]:
#Lectura de archivos
departamentos = pd.read_csv(url_departamentos)
empleados = pd.read_csv(url_empleados)
salarios = pd.read_csv(url_salarios)

In [6]:
departamentos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_departamento  9 non-null      object
 1   departamento     9 non-null      object
 2   ubicacion        9 non-null      object
dtypes: object(3)
memory usage: 348.0+ bytes

In [7]:
empleados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_empleado      136 non-null    object
 1   nombre           136 non-null    object
 2   id_departamento  129 non-null    object
 3   fecha_ingreso    132 non-null    object
dtypes: object(4)
memory usage: 4.4+ KB

In [8]:
salarios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_salario   136 non-null    object
 1   id_empleado  130 non-null    object
 2   salario      130 non-null    object
 3   bono         132 non-null    object
dtypes: object(4)
memory usage: 4.4+ KB

# EXPLORACION DE DATOS

In [9]:
print("Dimensiones del dataset departamentos(filas, columnas)")
print(departamentos.shape)

Dimensiones del dataset departamentos(filas, columnas)
(9, 3)

In [10]:
departamentos.head()

  id_departamento departamento   ubicacion
0             D10          TI   Edificio A
1             D11     Finanzas      Remoto
2             D12         RRHH  Edificio A
3             D13       Ventas  Edificio A
4             D14      Compras  Edificio A

In [11]:
print("tipo de datos de cada columna")
print(departamentos.dtypes)

tipo de datos de cada columna
id_departamento    object
departamento       object
ubicacion          object
dtype: object

In [12]:
print("Valores nulos por columna")
print(departamentos.isnull().sum())

Valores nulos por columna
id_departamento    0
departamento       0
ubicacion          0
dtype: int64

In [13]:
print("Valores duplicados")
print(departamentos.duplicated().sum())

Valores duplicados
1

In [14]:
#Ver los archivos duplicados
departamentos.duplicated(keep=False)

0    False
1     True
2    False
3    False
4    False
5    False
6    False
7    False
8     True
dtype: bool

# LIMPIEZA DE DEPARTAMENTOS

In [15]:
#copia de archivo departamentos
departamentos_limpio = departamentos.copy()

In [16]:
def normalizar_columnas(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )
    return df

In [17]:
def limpiar_texto_basico(df):
    for col in df.select_dtypes(include="object").columns:
        df[col] = df[col].astype(str).str.strip()
        df[col] = df[col].replace(
            ["nan", "None", "NULL", "null", "", "NaN", "N/A", "na"],
            pd.NA
        )
    return df

In [22]:
departamentos_limpio = normalizar_columnas(departamentos_limpio)
departamentos_limpio = limpiar_texto_basico(departamentos_limpio)

In [23]:
# Eliminar duplicados
departamentos_limpio = departamentos_limpio.drop_duplicates()

In [24]:
# Separar validos de rechazados
validos = departamentos_limpio[
    departamentos_limpio["id_departamento"].notna() &
    departamentos_limpio["departamento"].notna()
].copy()

rechazados = departamentos_limpio[
    departamentos_limpio["id_departamento"].isna() |
    departamentos_limpio["departamento"].isna()
].copy()

In [26]:
#Agregando motivo de rechazo
if len(rechazados) > 0:
    def motivo_rechazo(row):
        motivos = []
        if pd.isna(row["id_departamento"]):
            motivos.append("id_departamento_vacio")
        if pd.isna(row["departamento"]):
            motivos.append("departamento_vacio")
        return ",".join(motivos)

In [29]:
#Exportando archivos
validos.to_csv("D_departamentos_curated.csv", index=False)
rechazados.to_csv("D_departamentos_rejects.csv", index=False)

In [30]:
#Descarga de archivos
from google.colab import files
files.download("D_departamentos_curated.csv")
files.download("D_departamentos_rejects.csv")

# LIMPIEZA DE EMPLEADOS

In [48]:
print("\n Información general:")
print(empleados.info())

 Información general:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_empleado      136 non-null    object
 1   nombre           136 non-null    object
 2   id_departamento  129 non-null    object
 3   fecha_ingreso    132 non-null    object
dtypes: object(4)
memory usage: 4.4+ KB
None

In [49]:
print("\n Primeras 10 filas:")
print(empleados.head(10))

 Primeras 10 filas:
  id_empleado           nombre id_departamento fecha_ingreso
0       EM400     Marta Romero             D10    2023-09-12
1       EM401     José Ramírez             D15    2022-09-26
2       EM402    Miguel Romero             D10    2020-02-02
3       EM403      Elena Rivas             D99    2020-01-14
4       EM404   Fernando Rivas             D13    2022-12-25
5       EM405  Diego Hernández             D12    2023-02-03
6       EM406   Adriana Santos             D99    2022-04-22
7       EM407    Sofía Mendoza             D13    2020/01/25
8       EM408     María Torres             D14    2020-02-04
9       EM409      Paola Rivas             D11    2022-12-20

In [50]:
print("\n Valores nulos:")
print(empleados.isnull().sum())

 Valores nulos:
id_empleado        0
nombre             0
id_departamento    7
fecha_ingreso      4
dtype: int64

In [51]:
print("\n Registros duplicados (por id_empleado):")
print(f"   Duplicados totales: {empleados.duplicated().sum()}")
print(f"   IDs duplicados: {empleados['id_empleado'].duplicated().sum()}")

 Registros duplicados (por id_empleado):
   Duplicados totales: 6
   IDs duplicados: 6

In [52]:
print("\n Valores únicos en id_departamento:")
print(empleados['id_departamento'].value_counts(dropna=False))

 Valores únicos en id_departamento:
id_departamento
D13    23
D10    21
D15    19
D14    16
D11    13
D17    12
D12    11
D16    10
NaN     7
D99     4
Name: count, dtype: int64

In [53]:
print("\n Ejemplos de fechas (primeros 15 valores no nulos):")
fechas_muestra = empleados['fecha_ingreso'].dropna().head(15).tolist()
print(fechas_muestra)

 Ejemplos de fechas (primeros 15 valores no nulos):
['2023-09-12', '2022-09-26', '2020-02-02', '2020-01-14', '2022-12-25', '2023-02-03', '2022-04-22', '2020/01/25', '2020-02-04', '2022-12-20', '2024-01-19', '2021-07-16', '2023-01-02', '2021-08-10', '2020-02-05']

In [54]:
print("\n IDs de empleado con posibles problemas (nulos o formato raro):")
print(empleados[empleados['id_empleado'].isna() | (empleados['id_empleado'].astype(str).str.len() < 5)])

 IDs de empleado con posibles problemas (nulos o formato raro):
Empty DataFrame
Columns: [id_empleado, nombre, id_departamento, fecha_ingreso]
Index: []

In [56]:
#copia de archivo
empleados_limpio = empleados.copy()

In [57]:
# Normalizar columnas
empleados_limpio.columns = (
    empleados_limpio.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [58]:
# Limpiar texto
for col in empleados_limpio.select_dtypes(include="object").columns:
    empleados_limpio[col] = empleados_limpio[col].astype(str).str.strip()
    empleados_limpio[col] = empleados_limpio[col].replace(
        ["nan", "None", "NULL", "null", "", "NaN", "N/A", "na"],
        pd.NA
    )

In [59]:
# Eliminar duplicados
empleados_limpio = empleados_limpio.drop_duplicates()

In [62]:
#  CONVERTIR FECHA_INGRESO
# ============================================
def convertir_fecha(fecha):
    if pd.isna(fecha):
        return np.nan
    try:
        return pd.to_datetime(fecha, errors='coerce')
    except:
        return np.nan

In [61]:
empleados_limpio["fecha_ingreso"] = empleados_limpio["fecha_ingreso"].apply(convertir_fecha)

In [64]:
# Cargar departamentos curados para validar ids
url_departamentos_curated = "https://raw.githubusercontent.com/davidromero2534582021/etl-data-pipeline-2534582021/refs/heads/main/data/curated/D_departamentos_curated.csv"
departamentos_validos = pd.read_csv(url_departamentos_curated)
ids_departamentos_validos = departamentos_validos["id_departamento"].tolist()

In [66]:
#  archivos validos
# Reglas: id_empleado no nulo, id_departamento válido (existe en departamentos), fecha_ingreso válida
validos = empleados_limpio[
    empleados_limpio["id_empleado"].notna() &
    empleados_limpio["id_departamento"].notna() &
    empleados_limpio["id_departamento"].isin(ids_departamentos_validos) &
    empleados_limpio["fecha_ingreso"].notna()
].copy()

In [67]:
#archivos rechazados
rechazados = empleados_limpio[
    empleados_limpio["id_empleado"].isna() |
    empleados_limpio["id_departamento"].isna() |
    (~empleados_limpio["id_departamento"].isin(ids_departamentos_validos)) |
    empleados_limpio["fecha_ingreso"].isna()
].copy()

In [68]:
# agregar motivo de rechazo

if len(rechazados) > 0:
    def motivo_rechazo_empleado(row):
        motivos = []
        if pd.isna(row["id_empleado"]):
            motivos.append("id_empleado_vacio")
        if pd.isna(row["id_departamento"]):
            motivos.append("id_departamento_vacio")
        elif row["id_departamento"] not in ids_departamentos_validos:
            motivos.append(f"departamento_{row['id_departamento']}_no_existe")
        if pd.isna(row["fecha_ingreso"]):
            motivos.append("fecha_ingreso_invalida")
        return ",".join(motivos)

In [69]:
 rechazados["motivo_rechazo"] = rechazados.apply(motivo_rechazo_empleado, axis=1)

In [70]:
# exportando archivos

validos.to_csv("D_empleados_curated.csv", index=False)
rechazados.to_csv("D_empleados_rejects.csv", index=False)

print(f" Válidos: {len(validos)}")
print(f" Rechazados: {len(rechazados)}")

print("\n Motivos de rechazo:")
if len(rechazados) > 0:
    print(rechazados["motivo_rechazo"].value_counts())

 Válidos: 109
 Rechazados: 21

 Motivos de rechazo:
motivo_rechazo
fecha_ingreso_invalida        11
id_departamento_vacio          7
departamento_D99_no_existe     3
Name: count, dtype: int64

In [71]:
# Descargar
files.download("D_empleados_curated.csv")
files.download("D_empleados_rejects.csv")

# LIMPIEZA DE SALARIOS

In [39]:
print("\n Información general:")
print(salarios.info())

 Información general:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_salario   136 non-null    object
 1   id_empleado  130 non-null    object
 2   salario      130 non-null    object
 3   bono         132 non-null    object
dtypes: object(4)
memory usage: 4.4+ KB
None

In [40]:
print("\n Primeras 10 filas:")
print(salarios.head(10))

 Primeras 10 filas:
  id_salario id_empleado  salario    bono
0      S6000       EM432   586.98  281.04
1      S6001       EM454      NaN  473.55
2      S6002       EM406  1583.76  248.13
3      S6003       EM456   1647.0  190.26
4      S6004       EM525  2750.51   81.52
5      S6005       EM411   3251.2   393.1
6      S6006       EM415  3350.33     NaN
7      S6007       EM442  2210.22  192.18
8      S6008       EM516  1539.22    12.6
9      S6009         NaN  2852.02   419.5

In [41]:
print("\n Valores nulos:")
print(salarios.isnull().sum())

 Valores nulos:
id_salario     0
id_empleado    6
salario        6
bono           4
dtype: int64

In [42]:
print("\n Registros duplicados:")
print(f"   Duplicados totales: {salarios.duplicated().sum()}")

 Registros duplicados:
   Duplicados totales: 6

In [43]:
print("\n Valores únicos en id_empleado (vs total de empleados):")
print(f"   IDs únicos en salarios: {salarios['id_empleado'].nunique()}")
print(f"   IDs nulos: {salarios['id_empleado'].isna().sum()}")

 Valores únicos en id_empleado (vs total de empleados):
   IDs únicos en salarios: 85
   IDs nulos: 6

In [44]:
print("\n Ejemplos de salario (primeros 10 valores no nulos):")
print(salarios['salario'].dropna().head(10).tolist())

 Ejemplos de salario (primeros 10 valores no nulos):
['586.98', '1583.76', '1647.0', '2750.51', '3251.2', '3350.33', '2210.22', '1539.22', '2852.02', '1215.55']

In [45]:
print("\n Ejemplos de bono (primeros 10 valores no nulos):")
print(salarios['bono'].dropna().head(10).tolist())

 Ejemplos de bono (primeros 10 valores no nulos):
['281.04', '473.55', '248.13', '190.26', '81.52', '393.1', '192.18', '12.6', '419.5', '5.71']

In [46]:
print("\n IDs de salario con formato raro:")
ids_raros = salarios[~salarios['id_salario'].astype(str).str.match(r'^S\d+$', na=False)]
print(ids_raros[['id_salario', 'id_empleado']].head(10))

 IDs de salario con formato raro:
Empty DataFrame
Columns: [id_salario, id_empleado]
Index: []

In [73]:
# Cargar empleados curados para validar ids
url_empleados_curated = "https://raw.githubusercontent.com/davidromero2534582021/etl-data-pipeline-2534582021/refs/heads/main/data/curated/D_empleados_curated.csv"
empleados_validos = pd.read_csv(url_empleados_curated)
ids_empleados_validos = empleados_validos["id_empleado"].tolist()

In [74]:
#Realizando copia de archivo
salarios_limpio = salarios.copy()

In [75]:
# Normalizar columnas
salarios_limpio.columns = (
    salarios_limpio.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [76]:
# Limpiar texto
for col in salarios_limpio.select_dtypes(include="object").columns:
    salarios_limpio[col] = salarios_limpio[col].astype(str).str.strip()
    salarios_limpio[col] = salarios_limpio[col].replace(
        ["nan", "None", "NULL", "null", "", "NaN", "N/A", "na"],
        pd.NA
    )

In [77]:
# Eliminar duplicados
salarios_limpio = salarios_limpio.drop_duplicates()

In [78]:
#  convertir salario y bono a tipo numero

def convertir_numero(valor):
    if pd.isna(valor):
        return np.nan
    try:
        return float(valor)
    except:
        return np.nan

In [79]:
salarios_limpio["salario"] = salarios_limpio["salario"].apply(convertir_numero)
salarios_limpio["bono"] = salarios_limpio["bono"].apply(convertir_numero)

In [80]:
# 4. separamos validos de rechazados

# Reglas: id_empleado válido (existe en empleados), salario no nulo y > 0
validos = salarios_limpio[
    salarios_limpio["id_empleado"].notna() &
    salarios_limpio["id_empleado"].isin(ids_empleados_validos) &
    salarios_limpio["salario"].notna() &
    (salarios_limpio["salario"] > 0)
].copy()

rechazados = salarios_limpio[
    salarios_limpio["id_empleado"].isna() |
    (~salarios_limpio["id_empleado"].isin(ids_empleados_validos)) |
    salarios_limpio["salario"].isna() |
    (salarios_limpio["salario"] <= 0)
].copy()

In [81]:
#Motivo de rechazo
if len(rechazados) > 0:
    def motivo_rechazo_salario(row):
        motivos = []
        if pd.isna(row["id_empleado"]):
            motivos.append("id_empleado_vacio")
        elif row["id_empleado"] not in ids_empleados_validos:
            motivos.append("id_empleado_no_existe")
        if pd.isna(row["salario"]):
            motivos.append("salario_vacio")
        elif row["salario"] <= 0:
            motivos.append("salario_invalido")
        return ",".join(motivos)

    rechazados["motivo_rechazo"] = rechazados.apply(motivo_rechazo_salario, axis=1)

In [95]:
def limpiar_bono(valor):
    if pd.isna(valor):
        return np.nan

    valor_str = str(valor).strip().lower()
    if valor_str in ["", "nan", "none", "null", "sin bono", "n/a"]:
        return np.nan

        # Extraer número de texto como "273.22 USD"
    numeros = re.findall(r'\d+\.?\d*', valor_str)
    if numeros:
        try:
            return float(numeros[0])
        except:
            return np.nan

    # Intentar conversión directa
    try:
        return float(valor_str)
    except:
        return np.nan

In [96]:
# Limpiar texto
for col in salarios_limpio.select_dtypes(include="object").columns:
    salarios_limpio[col] = salarios_limpio[col].astype(str).str.strip()
    salarios_limpio[col] = salarios_limpio[col].replace(
        ["nan", "None", "NULL", "null", "", "NaN", "N/A", "na"],
        pd.NA
    )

In [97]:
# Eliminar duplicados
salarios_limpio = salarios_limpio.drop_duplicates()

In [98]:
# convertir salario y bono

def convertir_numero(valor):
    if pd.isna(valor):
        return np.nan
    try:
        return float(valor)
    except:
        return np.nan

In [100]:
# Aplicar limpieza
salarios_limpio["salario"] = salarios_limpio["salario"].apply(convertir_numero)
salarios_limpio["bono"] = salarios_limpio["bono"].apply(limpiar_bono)

In [102]:
# separar validos de rechazados

# Reglas: id_empleado válido, salario no nulo y > 0
validos = salarios_limpio[
    salarios_limpio["id_empleado"].notna() &
    salarios_limpio["id_empleado"].isin(ids_empleados_validos) &
    salarios_limpio["salario"].notna() &
    (salarios_limpio["salario"] > 0)
].copy()

rechazados = salarios_limpio[
    salarios_limpio["id_empleado"].isna() |
    (~salarios_limpio["id_empleado"].isin(ids_empleados_validos)) |
    salarios_limpio["salario"].isna() |
    (salarios_limpio["salario"] <= 0)
].copy()

In [103]:
#motivo de rechazo

if len(rechazados) > 0:
    def motivo_rechazo_salario(row):
        motivos = []
        if pd.isna(row["id_empleado"]):
            motivos.append("id_empleado_vacio")
        elif row["id_empleado"] not in ids_empleados_validos:
            motivos.append("id_empleado_no_existe")
        if pd.isna(row["salario"]):
            motivos.append("salario_vacio")
        elif row["salario"] <= 0:
            motivos.append("salario_invalido")
        return ",".join(motivos)

    rechazados["motivo_rechazo"] = rechazados.apply(motivo_rechazo_salario, axis=1)

In [104]:
# exportar

validos.to_csv("D_salarios_curated.csv", index=False)
rechazados.to_csv("D_salarios_rejects.csv", index=False)

In [105]:
# Descargar
files.download("D_salarios_curated.csv")
files.download("D_salarios_rejects.csv")

# CONEXION A BASE DE DATOS

In [109]:
#Conectar con Posgre
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_nu8y_user:MhUvzgn0RNlRIpHCo2CTQEZI8PhH2Vpy@dpg-d6qu6tv5gffc73f0dlng-a.oregon-postgres.render.com/etl_seguros_nu8y"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 51.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [111]:
#Cargarmos archivos curados
url_departamentosCurados = "https://raw.githubusercontent.com/davidromero2534582021/etl-data-pipeline-2534582021/refs/heads/main/data/curated/D_departamentos_curated.csv"
url_empleadosCurados = "https://raw.githubusercontent.com/davidromero2534582021/etl-data-pipeline-2534582021/refs/heads/main/data/curated/D_empleados_curated.csv"
url_salariosCurados = "https://raw.githubusercontent.com/davidromero2534582021/etl-data-pipeline-2534582021/refs/heads/main/data/curated/D_salarios_curated.csv"

In [112]:
departamentos = pd.read_csv(url_departamentosCurados)
empleados = pd.read_csv(url_empleadosCurados)
salarios = pd.read_csv(url_salariosCurados)

print(f"    departamentos: {len(departamentos)} registros")
print(f"    empleados: {len(empleados)} registros")
print(f"    salarios: {len(salarios)} registros")

    departamentos: 8 registros
    empleados: 109 registros
    salarios: 97 registros

# Creacion de tablas

In [113]:
# creacion de tablas

print("\n CREANDO TABLAS...")

create_tables_sql = """
DROP TABLE IF EXISTS salarios CASCADE;
DROP TABLE IF EXISTS empleados CASCADE;
DROP TABLE IF EXISTS departamentos CASCADE;

CREATE TABLE departamentos (
    id_departamento VARCHAR(10) PRIMARY KEY,
    departamento VARCHAR(100),
    ubicacion VARCHAR(100)
);

CREATE TABLE empleados (
    id_empleado VARCHAR(10) PRIMARY KEY,
    nombre VARCHAR(150),
    id_departamento VARCHAR(10),
    fecha_ingreso DATE
);

CREATE TABLE salarios (
    id_salario VARCHAR(10) PRIMARY KEY,
    id_empleado VARCHAR(10),
    salario NUMERIC(10,2),
    bono NUMERIC(10,2)
);
"""

with engine.connect() as conn:
    for comando in create_tables_sql.split(';'):
        if comando.strip():
            conn.execute(text(comando))
    conn.commit()
print(" Tablas creadas")

 CREANDO TABLAS...
 Tablas creadas

In [114]:
# limpieza adicional

print("\n LIMPIEZA FINAL DE DATOS...")

# Limpiar espacios en departamentos
departamentos['departamento'] = departamentos['departamento'].str.strip()
departamentos['ubicacion'] = departamentos['ubicacion'].str.strip()

# Convertir fecha_ingreso a formato DATE
empleados['fecha_ingreso'] = pd.to_datetime(empleados['fecha_ingreso'], errors='coerce')

# Asegurar que bono null se mantenga como None (NaN ya está bien)

print(" Datos preparados")


#carga de datos (respetando orden por FK)

print("\n📤 CARGANDO DATOS...")

# Orden: departamentos → empleados → salarios
try:
    departamentos.to_sql('departamentos', engine, if_exists='append', index=False)
    print(f"    departamentos: {len(departamentos)} registros")
except Exception as e:
    print(f"    Error en departamentos: {e}")

try:
    empleados.to_sql('empleados', engine, if_exists='append', index=False)
    print(f"    empleados: {len(empleados)} registros")
except Exception as e:
    print(f"    Error en empleados: {e}")

try:
    salarios.to_sql('salarios', engine, if_exists='append', index=False)
    print(f"    salarios: {len(salarios)} registros")
except Exception as e:
    print(f"    Error en salarios: {e}")

 LIMPIEZA FINAL DE DATOS...
 Datos preparados

📤 CARGANDO DATOS...
    departamentos: 8 registros
    empleados: 109 registros
    salarios: 97 registros

In [115]:
# verificar la carga

print("\n" + "=" * 70)
print(" VERIFICANDO CARGAS")
print("=" * 70)

conteos = pd.read_sql("""
    SELECT 'departamentos' as tabla, COUNT(*) FROM departamentos
    UNION ALL SELECT 'empleados', COUNT(*) FROM empleados
    UNION ALL SELECT 'salarios', COUNT(*) FROM salarios
    ORDER BY tabla;
""", engine)

print("\n REGISTROS POR TABLA:")
print(conteos.to_string(index=False))

======================================================================
 VERIFICANDO CARGAS
======================================================================

 REGISTROS POR TABLA:
        tabla  count
departamentos      8
    empleados    109
     salarios     97

# CONSULTAS DE VERIFICACION

In [116]:
# 7.1 Empleados por departamento
print("\n EMPLEADOS POR DEPARTAMENTO:")
query1 = """
    SELECT d.departamento, COUNT(e.id_empleado) as total
    FROM departamentos d
    LEFT JOIN empleados e ON d.id_departamento = e.id_departamento
    GROUP BY d.departamento
    ORDER BY total DESC;
"""
print(pd.read_sql(query1, engine).to_string(index=False))

 EMPLEADOS POR DEPARTAMENTO:
departamento  total
      Ventas     21
          TI     17
   Logística     17
     Compras     13
   Marketing     12
    Finanzas     12
   Auditoría      9
        RRHH      8

In [117]:
# 7.3 Empleados sin bono
print("\n EMPLEADOS SIN BONO (bono = NULL):")
query3 = """
    SELECT e.id_empleado, e.nombre, s.salario
    FROM empleados e
    JOIN salarios s ON e.id_empleado = s.id_empleado
    WHERE s.bono IS NULL;
"""
sin_bono = pd.read_sql(query3, engine)
print(f"   Total: {len(sin_bono)} empleados")
if len(sin_bono) > 0:
    print(sin_bono.head(10).to_string(index=False))

 EMPLEADOS SIN BONO (bono = NULL):
   Total: 8 empleados
id_empleado            nombre  salario
      EM408      María Torres  3062.44
      EM415    Adriana Santos  3350.33
      EM444      Jorge Torres  3172.30
      EM446    Paola Guerrero   667.03
      EM453       José Santos  1463.18
      EM485     Paola Morales  3295.42
      EM485     Paola Morales  1746.95
      EM493 Gabriela Guerrero  2284.74

In [120]:
empleados = pd.read_sql("SELECT * FROM empleados LIMIT 10", engine)
print(empleados.to_string(index=False))

id_empleado          nombre id_departamento fecha_ingreso
      EM400    Marta Romero             D10    2023-09-12
      EM401    José Ramírez             D15    2022-09-26
      EM402   Miguel Romero             D10    2020-02-02
      EM404  Fernando Rivas             D13    2022-12-25
      EM405 Diego Hernández             D12    2023-02-03
      EM407   Sofía Mendoza             D13    2020-01-25
      EM408    María Torres             D14    2020-02-04
      EM409     Paola Rivas             D11    2022-12-20
      EM410  Andrés Ramírez             D10    2024-01-19
      EM411 Natalia Vásquez             D14    2021-07-16